version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_DATABASE: 'test'
    ports:
      - 3306:3306
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 9000:9000
    networks:
      - internal
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8008:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    networks:
      - internal
networks:
  internal:
    driver: bridge